apiVersion: v1
kind: Service
metadata:
  name: sysprog-service
spec:
  type: LoadBalancer
  selector:
    app: sysprog-app
  ports:
    - protocol: TCP
      port: 8080       # Port used inside the cluster
      targetPort: 8080 # Port your C++ app listens on
      nodePort: 30005  # Fixed port for easy access